"""Tips and information about positions similar to the job offer."""

from __future__ import annotations

import json

from ..llm import LLMProvider, ask_json
from ..models import InsightsReport, JobOffer, Profile
from ..prompts import render_prompt
from .guard import check_terms
from .ingest import redact_for_prompt
from .job import language_name

DISCLAIMER = (
    "Generated by an LLM from its general knowledge — not live market data. "
    "Verify salaries, demand and requirements on current job boards."
)


def insights(
    job: JobOffer, profile: Profile, provider: LLMProvider, out_language: str = "en", max_retries: int = 2
) -> InsightsReport:
    prompt = render_prompt(
        "insights",
        out_language=language_name(out_language),
        redactions=profile.redactions,
        job_json=json.dumps(job.model_dump(exclude={"raw_text"}), ensure_ascii=False, indent=1),
        profile_json=redact_for_prompt(profile),
    )
    report = ask_json(provider, prompt, InsightsReport, max_retries)
    # insights are private to the candidate, but keep redacted names out anyway
    if check_terms(report.model_dump_json(), profile) and profile.redactions:
        data = report.model_dump_json()
        for t in profile.redactions:
            data = data.replace(t, "[redacted]")
        report = InsightsReport.model_validate_json(data)
    return report


def insights_markdown(report: InsightsReport, job: JobOffer) -> str:
    lines = [f"# Insights: {job.title}" + (f" @ {job.company}" if job.company else ""), "", f"> {DISCLAIMER}", ""]
    lines += ["## Similar positions to search for", *[f"- {t}" for t in report.related_titles], ""]
    lines += ["## Typical requirements in this role family", ""]
    lines += [
        f"- {'✅' if r.candidate_has else '⬜'} **{r.requirement}**" + (f" — {r.note}" if r.note else "")
        for r in report.typical_requirements
    ]
    lines += ["", "## What to learn next", *[f"{i}. {u}" for i, u in enumerate(report.upskilling, 1)], ""]
    lines += ["## Likely interview topics", ""]
    lines += [f"- **{t.topic}**" + (f" → {t.story}" if t.story else "") for t in report.interview_topics]
    if report.market_notes:
        lines += ["", "## Market notes", *[f"- {n}" for n in report.market_notes]]
    return "\n".join(lines) + "\n"
